### ISSUE TITLE
Send the images to an S3 like storage

### ISSUE THREAD

**Issue by fabien-h** [reactionimp/icemachinesplus#119]
Is there something we can do for the adapter to the s3 ?

We are going to have roughly 10k pictures to store, and that will be super heavy on the database (already is).

**Comment by aldeed** [comment]
Here's an issue in the file-collections repo with some details on how to create an S3 adapter: https://github.com/reactioncommerce/reaction-file-collections/issues/7

Once we have that, it should be as simple as importing and instantiating that adapter rather than GridFS here: https://github.com/reactioncommerce/reaction/blob/2b0c180e2e605a3afd9529a00a3a980eefc1f6c3/imports/plugins/core/files/server/fileCollections.js#L15

**Comment by fabien-h** [comment]
Nice.

Any timeframe for that feature ?

**Comment by vwadher** [comment]
Due to other priorities, this will not be implemented anytime soon but it is on our roadmap. I would suggest you implement this yourself if it’s a priority. Hopefully the above information helps guide you in the right direction.
